<div class="row">
    <div class="span12">
        <div id="reportrange">
            <i class="icon-calendar icon-large"></i>
            <span><?php echo date("F j, Y", strtotime('-30 day')); ?> - <?php echo date("F j, Y"); ?></span>
            <b class="caret"></b>
        </div>
    </div>
</div>


<div class="row">
    <div class="span12">
        <div class="btn-toolbar">
            <div class="btn-group">
                <a href="<?php echo $this->url('error'); ?>" class="btn">
                    <i class="icon-list"></i> Show All
                </a>
                <button class="btn dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <?php
                    foreach ($this->errors->getAccounts() as $account) {
                        foreach ($account->getMonitors()->getData() as $monitor) {
                            echo '<li><a href="' . $this->url(
                                    'error',
                                    array('action' => 'monitor', 'monitorId' => $monitor->getId())
                                ) . '">' . $monitor->getId() . ' ' . $monitor->getLabel() . '</a></li>';
                        }
                    }
                    ?>
                </ul>
            </div>

            <div class="btn-group pull-right">
                <a class="btn" href="#query1" data-toggle="modal"><i class="icon-globe"></i> Query</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="span12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th class="hidden-phone">ID</th>
                <th class="hidden-phone hidden-tablet">Open</th>
                <th class="hidden-phone hidden-tablet">Account</th>
                <th>Monitor</th>
                <th class="hidden-phone hidden-tablet">Url</th>
                <th>Result</th>
                <th class="hidden-phone">Duration</th>
                <th>Status</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($this->errors->getAccounts() as $account) {
                foreach ($account->getMonitors()->getData() as $monitor) {
                    foreach ($monitor->getErrors()->getData() as $error) {
                        echo '<tr>';
                        echo '<td class="hidden-phone">' . $error->getId() . '</td>';
                        echo '<td class="hidden-phone hidden-tablet">' . ($error->isOpen() ? 'Open' : 'Closed') . '</td>';
                        echo '<td class="hidden-phone hidden-tablet">' . $account->getName() . '</td>';
                        echo '<td>' . $monitor->getLabel() . '</td>';
                        echo '<td class="hidden-phone hidden-tablet">' . $this->shortenText($monitor->getUrl()) . '</td>';
                        echo '<td>' . $error->getResult() . '</td>';
                        echo '<td class="hidden-phone">' . $this->duration($error->getDuration()) . '</td>';
                        echo '<td>
                           <span class="disabled btn btn-small btn-fixed-width btn-' . $this->monitorStatus(
                                $error->getStatus()
                            ) . '">' . $error->getStatus() . '</span>
                          </td>';
                    }
                }
            }
            ?>
            </tbody>
        </table>
    </div>
</div>

<div id="query1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">API Query used</h3>
    </div>
    <div class="modal-body">
        https://api.siteconfidence.co.uk/current/[API-KEY]/Return/[Account[AccountId,Name,Pages[Page[Id,Url,Label,Notes,CurrentStatus,Errors[Open[Error[Id,Ref,LocalDateTime,StatusCode,Status,Notes,ResultCode,Result,Classification,Duration]],Closed[Count,Error[Id,Ref,LocalDateTime,StatusCode,Status,Notes,ResultCode,Result,Classification,Duration]]]]]]]/AccountId/[ACCOUNT-ID]/Format/json
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>