<div class="row">
    <div class="span12">
        <a class="btn" href="#query1" data-toggle="modal"><i class="icon-globe"></i> Query</a>
    </div>
</div>

<div class="row">
    <div class="span12">
        <h2>Login</h2>
        <div class="alert alert-block">
            Your credentials are not stored by this application
        </div>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('auth_login'));
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();

        echo $this->form()->openTag($form);

        echo $this->formHelper($form)->formInput($form->get('email'));
        echo $this->formHelper($form)->formInput($form->get('password'));

        echo '<div class="control-group">';
        echo '<div class="controls">';
        echo $this->formSubmit($form->get('submit'));
        echo '</div>';
        echo '</div>';

        echo $this->form()->closeTag();
        ?>
    </div>
</div>

<div id="query1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">API Query used</h3>
    </div>
    <div class="modal-body">
        https://api.siteconfidence.co.uk/current/username/[EMAIL]/password/[PASSWORD]/Format/json
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>