<div class="row">
    <div class="span12">
        <h2>Login</h2>
        <div class="alert alert-block">
            Your credentials are not stored by this application
        </div>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('auth',
                array(
                    'action' => 'login',
                )
            )
        );
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();

        echo $this->form()->openTag($form);

        echo $this->formHelper($form)->formInput($form->get('email'));
        echo $this->formHelper($form)->formInput($form->get('password'));

        echo '<div class="control-group">';
        echo '<div class="controls">';
        echo $this->formSubmit($form->get('submit'));
        echo '</div>';
        echo '</div>';

        echo $this->form()->closeTag();
        ?>
    </div>
</div>