<div class="row">
    <div class="span12">
        <a class="btn" href="#query1" data-toggle="modal"><i class="icon-globe"></i> Query</a>
    </div>
</div>

<div class="row">
    <div class="span12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Monitors</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($this->accounts->getAccounts() as $account) {
                echo '<tr>';
                echo '<td>' . $account->getId() . '</td>';
                echo '<td>' . $account->getName() . '</td>';
                echo '<td>
                       <a href="' . $this->url(
                        'monitor',
                        array('action' => 'account', 'accountId' => $account->getId())
                    ) . '" class="btn btn-small">Monitors</a>
                      </td>';
                echo '</tr>';
            }
            ?>
            </tbody>
        </table>

       
    </div>
</div>


<div id="query1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">API Query used</h3>
    </div>
    <div class="modal-body">
        https://api.siteconfidence.co.uk/current/[API-KEY]/Format/json
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>