<?php
$title = new HighCharts\Entity\Title();
$title->setText('Test Results');

$yAxisTitle = new HighCharts\Entity\Title();
$yAxisTitle->setText('Total Time');

$yAxis = new HighCharts\Entity\Yaxis();
$yAxis->setTitle($yAxisTitle);

$xAxis = new HighCharts\Entity\Xaxis();
$xAxis->setType('datetime');

$toolTip = new HighCharts\Entity\Tooltip();
$toolTip->setValueSuffix('(s)');

$startDateTime = new \DateTime($this->tests->getStartDate());

$seriesCollection = new HighCharts\Entity\SeriesCollection();
foreach ($this->tests->getMonitors() as $monitor) {
    $series = new HighCharts\Entity\Series();
    $series->setName($monitor->getLabel());
//        ->setPointStart($startDateTime->getTimestamp() * 1000)
//        ->setPointInterval(60*60*24*1000);

    $data = array();
    foreach ($monitor->getTests()->getData() as $test) {
        $date = new \DateTime($test->getDateTime());

        $data[] = array(
            'x' => $date->getTimestamp() * 1000,
            'y' => $test->getTotalSeconds()
        );
    }
    $series->setData($data);

    $seriesCollection->addSeries($series);
}

$highCharts = new HighCharts\Entity\HighChart();
$highCharts->setChart(new HighCharts\Entity\Chart())
    ->setTitle($title)
    ->setYAxis($yAxis)
    ->setXAxis($xAxis)
    ->setTooltip($toolTip)
    ->setLegend(new HighCharts\Entity\Legend())
    ->setSeries($seriesCollection);
?>

<div id="container"></div>

<script type="text/javascript" src="/js/highcharts.js"></script>
<script>
    $(function () {
        $('#container').highcharts(
              <?php echo $highCharts->getJson(); ?>
        );
    });
</script>