<div class="row">
    <div class="span12">
        <a class="btn" href="#query1" data-toggle="modal"><i class="icon-globe"></i> Query</a>
    </div>
</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Year', 'Sales', 'Expenses'],
            ['2004',  1000,      400],
            ['2005',  1170,      460],
            ['2006',  660,       1120],
            ['2007',  1030,      540]
        ]);

        var options = {
            title: 'Company Performance',
            hAxis: {title: 'Year', titleTextStyle: {color: 'red'}}
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>

<div class="row">
    <div class="span12">
        <div id="chart_div" style="width: 1100px; height: 600px;"></div>
    </div>
</div>

<div id="query1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">API Query used</h3>
    </div>
    <div class="modal-body">
        https://api.siteconfidence.co.uk/current/[API-KEY]/Return/[Account[Pages[Page[Id,Url,Label,CurrentStatus,DownloadSpeed,Alerting]]]]/AccountId/MN2A7711/Format/json
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>