<?php
$title = new HighCharts\Entity\Title();
$title->setText('Last 24hrs Download Time');

$subtitle = new HighCharts\Entity\Title();
$subtitle->setText($this->monitor->getLabel());

$yAxisTitle = new HighCharts\Entity\Title();
$yAxisTitle->setText('Total Time');

$yAxis = new HighCharts\Entity\Yaxis();
$yAxis->setTitle($yAxisTitle);

$xAxis = new HighCharts\Entity\Xaxis();
$xAxis->setType('datetime')
    ->setDateTimeLabelFormats(array(
            'hour' => '%H:%M'
        ));

$toolTip = new HighCharts\Entity\Tooltip();
$toolTip->setValueSuffix('(s)');

$seriesCollection = new HighCharts\Entity\SeriesCollection();
foreach ($this->monitor->getTestCollections() as $testCollection) {
    $series = new HighCharts\Entity\Series();
    $series->setName($testCollection->getDateRange());

    $data = array();
    foreach ($testCollection->getTests() as $test) {
        $date = new \DateTime($test->getDateTime());

        $data[] = array(
            'x' => $date->getTimestamp() * 1000,
            'y' => $test->getTotalSeconds()
        );
    }
    $series->setData($data);

    $seriesCollection->addSeries($series);
}

$chart = new HighCharts\Entity\Chart();
$chart->setType('spline');

$highCharts = new HighCharts\Entity\HighChart();
$highCharts->setChart($chart)
    ->setTitle($title)
    ->setSubTitle($subtitle)
    ->setYAxis($yAxis)
    ->setXAxis($xAxis)
    ->setTooltip($toolTip)
    ->setLegend(new HighCharts\Entity\Legend())
    ->setSeries($seriesCollection);
?>

<div id="container"></div>

<script type="text/javascript" src="/js/highcharts.js"></script>
<script>
    $(function () {
        $('#container').highcharts(
              <?php echo $highCharts->getJson(); ?>
        );
    });
</script>