<div class="hero-unit">
    <h1><?php echo $this->translate('NCC Group API'); ?></h1>
    <p><?php echo $this->translate('Simple Application using NCC Group API') ?></p>
    <p>
        <a class="btn btn-large" href="<?php echo $this->url(
            'monitor',
            array('action' => 'index')
        );?>"><?php echo $this->translate('My Monitors') ?> &raquo;</a>
    </p>
</div>

<div class="row">

    <div class="span6">
        <h2><?php echo $this->translate('This Project') ?></h2>
        <p><?php echo $this->translate('Code, Suggestion, Ideas, Contribution, please go to the Github page.') ?></p>
        <p><a class="btn" href="https://github.com/eddiejaoude/NCC-Group-API"><?php echo $this->translate('Github Project') ?> &raquo;</a></p>
    </div>

    <div class="span6">
        <h2><?php echo $this->translate('Web Page Test') ?></h2>
        <p><?php echo $this->translate('The API is a data extraction tool that allows NCC Group Web Performance customers the ability to access and extract their test results through standard XML and JSON requests. API Data requests can be used in anything from reporting spreadsheets through to live reporting applications, and is the recommended solution for advanced Monitoring customers to import live and historic data.') ?></p>
        <p><a class="btn" href="http://community.nccgroup-webperf.com/documentation/api-2/"><?php echo $this->translate('NCC Group API Docs') ?> &raquo;</a></p>
   </div>

</div>
