<div class="row">
    <div class="span12">
        <a class="btn" href="#saveAlertingStatus" data-toggle="modal"><i class="icon-download"></i> Save Status</a>
        <a class="btn" href="#query1" data-toggle="modal"><i class="icon-globe"></i> Query</a>
    </div>
</div>

<div class="row">
    <div class="span12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th class="hidden-phone">ID</th>
                <th>Label</th>
                <th class="hidden-phone hidden-tablet">Url</th>
                <th>Download</th>
                <th>Alerting</th>
                <th>Status</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($this->monitors->getAccounts() as $account) {
                foreach ($account->getMonitors()->getData() as $monitor) {
                    echo '<tr>';
                    echo '<td class="hidden-phone">' . $monitor->getId() . '</td>';
                    echo '<td>' . $monitor->getLabel() . '</td>';
                    echo '<td class="hidden-phone hidden-tablet">' . $this->shortenText($monitor->getUrl()) . '</td>';
                    echo '<td class="text-align-right">' . $monitor->getLatestTest()->getTotalSeconds() . 's</td>';
                    echo '<td><i class="icon-' . $this->monitorAlertingStatus($monitor->getAlerting()) . '"></i></td>';
                    echo '<td>
                           <a href="' . $this->url(
                            'test',
                            array('action' => 'index', 'monitorId' => $monitor->getId())
                        ) . '" class="btn btn-small btn-fixed-width btn-' . $this->monitorStatus(
                            $monitor->getStatus()
                        ) . '">' . $monitor->getStatus() . '</a>
                          </td>';
                    echo '</tr>';
                }
            }
            ?>
            </tbody>
        </table>
    </div>
</div>

<div id="saveAlertingStatus" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Save all monitors alerting status</h3>
    </div>
    <div class="modal-body">
        <input class="span2" id="prependedInput" type="text" placeholder="Alerting state label">
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button class="btn btn-primary">Save changes</button>
    </div>
</div>

<div id="query1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">API Query used</h3>
    </div>
    <div class="modal-body">
        https://api.siteconfidence.co.uk/current/[API-KEY]/Return/[Account[Pages[Page[Id,Url,Label,CurrentStatus,DownloadSpeed,Alerting]]]]/AccountId/MN2A7711/Format/json
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>